VALID_TARGETS = {'1', '2', '3', '4', '-'}
VALID_ELEMENTS = ('0', '1', '2', '3', '4', 'x', '-', 'f')
VALID_CONSUMABLES = 0
TIME_LIMIT = 3

HP = 150
SHIELD = 50

ATTACK_DAMAGE = 20
WALK_IN_PLAYER_DAMAGE = 20
PLAYER_WALKED_INTO_DAMAGE = 10

FIRE_DURATION_ON_MAP = 20
ON_FIRE_EFFECT_DURATION = 3
ON_FIRE_DAMAGE = 5

WALL_HP = 20
WALK_IN_WALL_DAMAGE = 20
WALL_TAKE_DAMAGE = 10
